/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/ignore/weapon/m4a1.glb -o src/components/Rendering/models/M4A1Gun.tsx 
Author: puresaltt (https://sketchfab.com/PureSaltt)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-colt-m4a1-de142447b4d047bbb0311c2974520f1e
Title: Low Poly Colt M4A1
*/

import * as THREE from 'three'
import { type JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import { type GLTF } from 'three-stdlib'
import { useKtx2LoaderExtender } from '../../../../lib/ktx2'
import { getAssetUrl } from '../../../../pathRegistry'

type GLTFResult = GLTF & {
  nodes: {
    Object_2: THREE.Mesh
    Object_3: THREE.Mesh
    Object_4: THREE.Mesh
    Object_5: THREE.Mesh
    Object_6: THREE.Mesh
  }
  materials: {
    Grey_Plastic: THREE.MeshStandardMaterial
    Black_Metal: THREE.MeshStandardMaterial
    Black_Plastic: THREE.MeshStandardMaterial
    Grey_Metal: THREE.MeshStandardMaterial
  }
}

const MODEL_URL = getAssetUrl('m4a1');

export function Model(props: JSX.IntrinsicElements['group']) {
  const extendWithKtx2 = useKtx2LoaderExtender()
  const { nodes, materials } = useGLTF(MODEL_URL, true, true, extendWithKtx2) as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <lineSegments geometry={nodes.Object_5.geometry} material={materials.Grey_Metal} />
        <mesh geometry={nodes.Object_2.geometry} material={materials.Grey_Plastic} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.Black_Metal} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.Black_Plastic} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.Grey_Metal} />
      </group>
    </group>
  )
}

