/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/ignore/creatures/animated-haunted-zombie.glb -o src/components/Rendering/models/creature/BoneClawUndead.tsx 
Author: Sealife Fan 3 (https://sketchfab.com/SealifeFan3)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/fully-reanimated-scp-096-updated-2926158b559d4228a421ddccf7dd5518
Title: Fully Reanimated SCP-096 (Updated!)
*/

import * as THREE from 'three'
import React, { useRef, type JSX } from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { type GLTF, SkeletonUtils } from 'three-stdlib'
import { getAssetUrl } from '../../../../pathRegistry'
import { useKtx2LoaderExtender } from '../../../../lib/ktx2'

type ActionName = 'Sit' | 'Wipe Tears' | 'Getting Up' | 'Idle Near' | 'Walk Near' | 'Walk' | 'Idle' | 'Panic Start' | 'Panic' | 'Panic End' | 'Running' | 'Attack Run Start' | 'Attack Run' | 'Attack' | 'Swing' | 'Sit 2 Start' | 'Sit 2' | 'Get Up Panic Start New' | 'Get Up Panic Start'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    Object_12: THREE.SkinnedMesh
    Object_13: THREE.SkinnedMesh
    _rootJoint: THREE.Bone
  }
  materials: {
    ['SCP096.png']: THREE.MeshStandardMaterial
    ['SCP096EYES.png']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

const MODEL_URL = getAssetUrl('animated-haunted-zombie')

export function BoneClawUndead(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group | null>(null)
  const extendWithKtx2 = useKtx2LoaderExtender()
  const { scene, animations } = useGLTF(MODEL_URL, true, true, extendWithKtx2)
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone) as unknown as GLTFResult
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={0.366}>
          <group name="bc03a9a4e23143bd9c69d7a70429f361fbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="scp096_skeleton001" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <group name="Object_9">
                    <primitive object={nodes._rootJoint} />
                    <skinnedMesh name="Object_12" geometry={nodes.Object_12.geometry} material={materials['SCP096.png']} skeleton={nodes.Object_12.skeleton} />
                    <skinnedMesh name="Object_13" geometry={nodes.Object_13.geometry} material={materials['SCP096EYES.png']} skeleton={nodes.Object_13.skeleton} />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}
