/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/ignore/creatures/girl_nilou.glb -o src/components/Rendering/models/creature/GirlNilou.tsx 
Author: ilyakardailskiy (https://sketchfab.com/ilyakardailskiy)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/nilou-1-genshin-impact-d79c23bf868140c0ba26c73a4aeaf304
Title: Nilou 1 Genshin Impact
*/

import * as THREE from 'three'
import { useMemo, type JSX } from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { type GLTF, SkeletonUtils } from 'three-stdlib'
import { getAssetUrl } from '../../../../pathRegistry'
import { useKtx2LoaderExtender } from '../../../../lib/ktx2'

type GLTFResult = GLTF & {
  nodes: {
    Object_7: THREE.SkinnedMesh
    Object_9: THREE.SkinnedMesh
    Object_11: THREE.SkinnedMesh
    Object_13: THREE.SkinnedMesh
    Object_15: THREE.SkinnedMesh
    Object_17: THREE.SkinnedMesh
    Object_19: THREE.SkinnedMesh
    Object_21: THREE.SkinnedMesh
    Object_23: THREE.SkinnedMesh
    Object_25: THREE.SkinnedMesh
    Object_27: THREE.SkinnedMesh
    Object_29: THREE.SkinnedMesh
    Object_31: THREE.SkinnedMesh
    Object_33: THREE.SkinnedMesh
    Object_35: THREE.SkinnedMesh
    Object_37: THREE.SkinnedMesh
    Object_39: THREE.SkinnedMesh
    Object_41: THREE.SkinnedMesh
    Object_43: THREE.SkinnedMesh
    Object_45: THREE.SkinnedMesh
    Object_47: THREE.SkinnedMesh
    Object_49: THREE.SkinnedMesh
    Object_51: THREE.SkinnedMesh
    Object_53: THREE.SkinnedMesh
    Object_55: THREE.SkinnedMesh
    Object_57: THREE.SkinnedMesh
    Object_59: THREE.SkinnedMesh
    Object_61: THREE.SkinnedMesh
    Object_63: THREE.SkinnedMesh
    Object_65: THREE.SkinnedMesh
    Object_67: THREE.SkinnedMesh
    Object_69: THREE.SkinnedMesh
    _rootJoint: THREE.Bone
  }
  materials: {
    No_Name: THREE.MeshStandardMaterial
    New_Material_Variant: THREE.MeshStandardMaterial
    New_Material_Variant_Variant_Variant_Variant_Variant: THREE.MeshStandardMaterial
  }
}

const MODEL_URL = getAssetUrl('girl_nilou')

export function GirlNilou(props: JSX.IntrinsicElements['group']) {
  const extendWithKtx2 = useKtx2LoaderExtender()
  const { scene } = useGLTF(MODEL_URL, true, true, extendWithKtx2)
  const clone = useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone) as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group scale={33.156}>
          <primitive object={nodes._rootJoint} />
          <skinnedMesh geometry={nodes.Object_7.geometry} material={materials.No_Name} skeleton={nodes.Object_7.skeleton} />
          <skinnedMesh geometry={nodes.Object_9.geometry} material={materials.New_Material_Variant} skeleton={nodes.Object_9.skeleton} />
          <skinnedMesh geometry={nodes.Object_11.geometry} material={materials.New_Material_Variant_Variant_Variant_Variant_Variant} skeleton={nodes.Object_11.skeleton} />
          <skinnedMesh geometry={nodes.Object_13.geometry} material={materials.New_Material_Variant_Variant_Variant_Variant_Variant} skeleton={nodes.Object_13.skeleton} />
          <skinnedMesh geometry={nodes.Object_15.geometry} material={materials.New_Material_Variant} skeleton={nodes.Object_15.skeleton} />
          <skinnedMesh geometry={nodes.Object_17.geometry} material={materials.New_Material_Variant_Variant_Variant_Variant_Variant} skeleton={nodes.Object_17.skeleton} />
          <skinnedMesh geometry={nodes.Object_19.geometry} material={materials.No_Name} skeleton={nodes.Object_19.skeleton} />
          <skinnedMesh geometry={nodes.Object_21.geometry} material={materials.No_Name} skeleton={nodes.Object_21.skeleton} />
          <skinnedMesh geometry={nodes.Object_23.geometry} material={materials.New_Material_Variant_Variant_Variant_Variant_Variant} skeleton={nodes.Object_23.skeleton} />
          <skinnedMesh geometry={nodes.Object_25.geometry} material={materials.New_Material_Variant} skeleton={nodes.Object_25.skeleton} />
          <skinnedMesh geometry={nodes.Object_27.geometry} material={materials.New_Material_Variant_Variant_Variant_Variant_Variant} skeleton={nodes.Object_27.skeleton} />
          <skinnedMesh geometry={nodes.Object_29.geometry} material={materials.New_Material_Variant_Variant_Variant_Variant_Variant} skeleton={nodes.Object_29.skeleton} />
          <skinnedMesh geometry={nodes.Object_31.geometry} material={materials.New_Material_Variant} skeleton={nodes.Object_31.skeleton} />
          <skinnedMesh geometry={nodes.Object_33.geometry} material={materials.New_Material_Variant} skeleton={nodes.Object_33.skeleton} />
          <skinnedMesh geometry={nodes.Object_35.geometry} material={materials.No_Name} skeleton={nodes.Object_35.skeleton} />
          <skinnedMesh geometry={nodes.Object_37.geometry} material={materials.No_Name} skeleton={nodes.Object_37.skeleton} />
          <skinnedMesh geometry={nodes.Object_39.geometry} material={materials.New_Material_Variant_Variant_Variant_Variant_Variant} skeleton={nodes.Object_39.skeleton} />
          <skinnedMesh geometry={nodes.Object_41.geometry} material={materials.No_Name} skeleton={nodes.Object_41.skeleton} />
          <skinnedMesh geometry={nodes.Object_43.geometry} material={materials.No_Name} skeleton={nodes.Object_43.skeleton} />
          <skinnedMesh geometry={nodes.Object_45.geometry} material={materials.New_Material_Variant} skeleton={nodes.Object_45.skeleton} />
          <skinnedMesh geometry={nodes.Object_47.geometry} material={materials.New_Material_Variant} skeleton={nodes.Object_47.skeleton} />
          <skinnedMesh geometry={nodes.Object_49.geometry} material={materials.New_Material_Variant} skeleton={nodes.Object_49.skeleton} />
          <skinnedMesh geometry={nodes.Object_51.geometry} material={materials.No_Name} skeleton={nodes.Object_51.skeleton} />
          <skinnedMesh geometry={nodes.Object_53.geometry} material={materials.New_Material_Variant} skeleton={nodes.Object_53.skeleton} />
          <skinnedMesh geometry={nodes.Object_55.geometry} material={materials.New_Material_Variant} skeleton={nodes.Object_55.skeleton} />
          <skinnedMesh geometry={nodes.Object_57.geometry} material={materials.No_Name} skeleton={nodes.Object_57.skeleton} />
          <skinnedMesh geometry={nodes.Object_59.geometry} material={materials.No_Name} skeleton={nodes.Object_59.skeleton} />
          <skinnedMesh geometry={nodes.Object_61.geometry} material={materials.New_Material_Variant_Variant_Variant_Variant_Variant} skeleton={nodes.Object_61.skeleton} />
          <skinnedMesh geometry={nodes.Object_63.geometry} material={materials.No_Name} skeleton={nodes.Object_63.skeleton} />
          <skinnedMesh geometry={nodes.Object_65.geometry} material={materials.New_Material_Variant_Variant_Variant_Variant_Variant} skeleton={nodes.Object_65.skeleton} />
          <skinnedMesh geometry={nodes.Object_67.geometry} material={materials.New_Material_Variant} skeleton={nodes.Object_67.skeleton} />
          <skinnedMesh geometry={nodes.Object_69.geometry} material={materials.No_Name} skeleton={nodes.Object_69.skeleton} />
        </group>
      </group>
    </group>
  )
}
