/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/ignore/creatures/animated_bird_pigeon.glb -o src/components/Rendering/models/creature/Pigeon.tsx 
Author: dudecon (https://sketchfab.com/dudecon)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/animated-bird-pigeon-797d27b68af3453e865149435df6aa30
Title: Animated Bird, Pigeon
*/

import * as THREE from 'three'
import React, { useRef, type JSX } from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { type GLTF, SkeletonUtils } from 'three-stdlib'
import { getAssetUrl } from '../../../../pathRegistry'
import { useKtx2LoaderExtender } from '../../../../lib/ktx2'

type ActionName = 'BirdRig|Flapping' | 'BirdRig|Gliding' | 'BirdRig|Landing' | 'BirdRig|Standing Idle' | 'BirdRig|Takeoff'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    Object_144: THREE.SkinnedMesh
    _rootJoint: THREE.Bone
  }
  materials: {
    ['Material.002']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

const MODEL_URL = getAssetUrl('animated_bird_pigeon')

export function Pigeon(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group | null>(null)
  const extendWithKtx2 = useKtx2LoaderExtender()
  const { scene, animations } = useGLTF(MODEL_URL, true, true, extendWithKtx2)
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone) as unknown as GLTFResult
  // @ts-ignore
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={8.723}>
          <group name="bird_animation_tweaksfbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="BirdRig" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <group name="Object_5">
                    <primitive object={nodes._rootJoint} />
                    <skinnedMesh name="Object_144" geometry={nodes.Object_144.geometry} material={materials['Material.002']} skeleton={nodes.Object_144.skeleton} />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}
