/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/ignore/creatures/the_human_deer_animated_horror.glb -o src/components/Rendering/models/creature/Wendigo.tsx 
Author: ceeleste (https://sketchfab.com/ceeleste)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/the-human-deer-7644694337404bb18eb68e6b637740a1
Title: The Human Deer
*/

import * as THREE from 'three'
import React, { useRef, type JSX } from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { type GLTF, SkeletonUtils } from 'three-stdlib'
import { getAssetUrl } from '../../../../pathRegistry'
import { useKtx2LoaderExtender } from '../../../../lib/ktx2'

type ActionName = 'Take 001'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    R_leg_exposed_bone_low_Deer_body1_0: THREE.Mesh
    pPlane19_Hair_cards_0: THREE.Mesh
    Object_7: THREE.SkinnedMesh
    Object_9: THREE.SkinnedMesh
    Object_11: THREE.SkinnedMesh
    Object_13: THREE.SkinnedMesh
    Object_15: THREE.SkinnedMesh
    Object_17: THREE.SkinnedMesh
    Object_19: THREE.SkinnedMesh
    Object_21: THREE.SkinnedMesh
    Object_23: THREE.SkinnedMesh
    Object_25: THREE.SkinnedMesh
    Object_27: THREE.SkinnedMesh
    Object_29: THREE.SkinnedMesh
    Object_31: THREE.SkinnedMesh
    Object_33: THREE.SkinnedMesh
    Object_35: THREE.SkinnedMesh
    Object_37: THREE.SkinnedMesh
    Object_39: THREE.SkinnedMesh
    Object_41: THREE.SkinnedMesh
    Object_43: THREE.SkinnedMesh
    Object_45: THREE.SkinnedMesh
    Object_47: THREE.SkinnedMesh
    Object_49: THREE.SkinnedMesh
    Object_51: THREE.SkinnedMesh
    Object_53: THREE.SkinnedMesh
    Object_55: THREE.SkinnedMesh
    Object_57: THREE.SkinnedMesh
    Object_59: THREE.SkinnedMesh
    Object_61: THREE.SkinnedMesh
    Object_63: THREE.SkinnedMesh
    Object_65: THREE.SkinnedMesh
    Object_67: THREE.SkinnedMesh
    Object_69: THREE.SkinnedMesh
    Object_71: THREE.SkinnedMesh
    Object_73: THREE.SkinnedMesh
    Object_75: THREE.SkinnedMesh
    Object_77: THREE.SkinnedMesh
    Object_79: THREE.SkinnedMesh
    Object_81: THREE.SkinnedMesh
    Object_83: THREE.SkinnedMesh
    Object_85: THREE.SkinnedMesh
    Object_87: THREE.SkinnedMesh
    Object_89: THREE.SkinnedMesh
    Object_91: THREE.SkinnedMesh
    Object_93: THREE.SkinnedMesh
    Object_95: THREE.SkinnedMesh
    Object_97: THREE.SkinnedMesh
    Object_99: THREE.SkinnedMesh
    Object_101: THREE.SkinnedMesh
    Object_103: THREE.SkinnedMesh
    Object_105: THREE.SkinnedMesh
    Object_107: THREE.SkinnedMesh
    Object_109: THREE.SkinnedMesh
    Object_111: THREE.SkinnedMesh
    Object_113: THREE.SkinnedMesh
    Object_115: THREE.SkinnedMesh
    Object_117: THREE.SkinnedMesh
    Object_119: THREE.SkinnedMesh
    Object_121: THREE.SkinnedMesh
    Object_123: THREE.SkinnedMesh
    Object_125: THREE.SkinnedMesh
    Object_127: THREE.SkinnedMesh
    Object_129: THREE.SkinnedMesh
    Object_131: THREE.SkinnedMesh
    Object_133: THREE.SkinnedMesh
    Object_135: THREE.SkinnedMesh
    Object_137: THREE.SkinnedMesh
    Object_139: THREE.SkinnedMesh
    Object_141: THREE.SkinnedMesh
    Object_143: THREE.SkinnedMesh
    Object_145: THREE.SkinnedMesh
    _rootJoint: THREE.Bone
  }
  materials: {
    Deer_body1: THREE.MeshStandardMaterial
    Hair_cards: THREE.MeshStandardMaterial
    Deer_head1: THREE.MeshStandardMaterial
    hair_cards_v2: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

const MODEL_URL = getAssetUrl("the_human_deer_animated_horror")

export function Wendigo(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group | null>(null)
  const extendWithKtx2 = useKtx2LoaderExtender()
  const { scene, animations } = useGLTF(MODEL_URL, true, true, extendWithKtx2);
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone) as unknown as GLTFResult
  // @ts-ignore
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={0.054}>
          <group name="861464ccda3242dbbf70ce64cb5779b0fbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Object_4">
                  <primitive object={nodes._rootJoint} />
                  <group name="Body_low">
                    <group name="R_leg_exposed_bone_low" position={[1558.193, -3715.27, 6449.197]} rotation={[0.012, -0.013, 0.276]}>
                      <mesh name="R_leg_exposed_bone_low_Deer_body1_0" geometry={nodes.R_leg_exposed_bone_low_Deer_body1_0.geometry} material={materials.Deer_body1} />
                    </group>
                  </group>
                  <group name="Root_grp_ctrl">
                    <group name="Root_ctrl" position={[34.317, 7.083, -402.462]} scale={1.001}>
                      <group name="C_Hip_grp_ctrl" position={[0, -1152.1, 6092.469]} rotation={[2.657, Math.PI / 2, 0]}>
                        <group name="C_Hip_ctrl" position={[922.489, 931.942, 137.25]} />
                      </group>
                    </group>
                  </group>
                  <group name="body_hir_cards">
                    <group name="pPlane19" position={[1000.566, -2295.528, 5063.551]} rotation={[-0.371, -0.366, -0.259]} scale={0.536}>
                      <mesh name="pPlane19_Hair_cards_0" geometry={nodes.pPlane19_Hair_cards_0.geometry} material={materials.Hair_cards} />
                    </group>
                  </group>
                  <skinnedMesh name="Object_7" geometry={nodes.Object_7.geometry} material={materials.Deer_body1} skeleton={nodes.Object_7.skeleton} />
                  <skinnedMesh name="Object_9" geometry={nodes.Object_9.geometry} material={materials.Deer_body1} skeleton={nodes.Object_9.skeleton} />
                  <skinnedMesh name="Object_11" geometry={nodes.Object_11.geometry} material={materials.Deer_body1} skeleton={nodes.Object_11.skeleton} />
                  <skinnedMesh name="Object_13" geometry={nodes.Object_13.geometry} material={materials.Deer_body1} skeleton={nodes.Object_13.skeleton} />
                  <skinnedMesh name="Object_15" geometry={nodes.Object_15.geometry} material={materials.Deer_body1} skeleton={nodes.Object_15.skeleton} />
                  <skinnedMesh name="Object_17" geometry={nodes.Object_17.geometry} material={materials.Deer_body1} skeleton={nodes.Object_17.skeleton} />
                  <skinnedMesh name="Object_19" geometry={nodes.Object_19.geometry} material={materials.Deer_body1} skeleton={nodes.Object_19.skeleton} />
                  <skinnedMesh name="Object_21" geometry={nodes.Object_21.geometry} material={materials.Deer_body1} skeleton={nodes.Object_21.skeleton} />
                  <skinnedMesh name="Object_23" geometry={nodes.Object_23.geometry} material={materials.Deer_body1} skeleton={nodes.Object_23.skeleton} />
                  <skinnedMesh name="Object_25" geometry={nodes.Object_25.geometry} material={materials.Deer_body1} skeleton={nodes.Object_25.skeleton} />
                  <skinnedMesh name="Object_27" geometry={nodes.Object_27.geometry} material={materials.Deer_body1} skeleton={nodes.Object_27.skeleton} />
                  <skinnedMesh name="Object_29" geometry={nodes.Object_29.geometry} material={materials.Deer_body1} skeleton={nodes.Object_29.skeleton} />
                  <skinnedMesh name="Object_31" geometry={nodes.Object_31.geometry} material={materials.Deer_body1} skeleton={nodes.Object_31.skeleton} />
                  <skinnedMesh name="Object_33" geometry={nodes.Object_33.geometry} material={materials.Deer_body1} skeleton={nodes.Object_33.skeleton} />
                  <skinnedMesh name="Object_35" geometry={nodes.Object_35.geometry} material={materials.Deer_body1} skeleton={nodes.Object_35.skeleton} />
                  <skinnedMesh name="Object_37" geometry={nodes.Object_37.geometry} material={materials.Deer_body1} skeleton={nodes.Object_37.skeleton} />
                  <skinnedMesh name="Object_39" geometry={nodes.Object_39.geometry} material={materials.Deer_body1} skeleton={nodes.Object_39.skeleton} />
                  <skinnedMesh name="Object_41" geometry={nodes.Object_41.geometry} material={materials.Deer_body1} skeleton={nodes.Object_41.skeleton} />
                  <skinnedMesh name="Object_43" geometry={nodes.Object_43.geometry} material={materials.Deer_body1} skeleton={nodes.Object_43.skeleton} />
                  <skinnedMesh name="Object_45" geometry={nodes.Object_45.geometry} material={materials.Deer_body1} skeleton={nodes.Object_45.skeleton} />
                  <skinnedMesh name="Object_47" geometry={nodes.Object_47.geometry} material={materials.Deer_body1} skeleton={nodes.Object_47.skeleton} />
                  <skinnedMesh name="Object_49" geometry={nodes.Object_49.geometry} material={materials.Deer_head1} skeleton={nodes.Object_49.skeleton} />
                  <skinnedMesh name="Object_51" geometry={nodes.Object_51.geometry} material={materials.Deer_head1} skeleton={nodes.Object_51.skeleton} />
                  <skinnedMesh name="Object_53" geometry={nodes.Object_53.geometry} material={materials.Deer_head1} skeleton={nodes.Object_53.skeleton} />
                  <skinnedMesh name="Object_55" geometry={nodes.Object_55.geometry} material={materials.Deer_head1} skeleton={nodes.Object_55.skeleton} />
                  <skinnedMesh name="Object_57" geometry={nodes.Object_57.geometry} material={materials.Deer_head1} skeleton={nodes.Object_57.skeleton} />
                  <skinnedMesh name="Object_59" geometry={nodes.Object_59.geometry} material={materials.Deer_head1} skeleton={nodes.Object_59.skeleton} />
                  <skinnedMesh name="Object_61" geometry={nodes.Object_61.geometry} material={materials.Deer_head1} skeleton={nodes.Object_61.skeleton} />
                  <skinnedMesh name="Object_63" geometry={nodes.Object_63.geometry} material={materials.Deer_head1} skeleton={nodes.Object_63.skeleton} />
                  <skinnedMesh name="Object_65" geometry={nodes.Object_65.geometry} material={materials.Deer_head1} skeleton={nodes.Object_65.skeleton} />
                  <skinnedMesh name="Object_67" geometry={nodes.Object_67.geometry} material={materials.Deer_head1} skeleton={nodes.Object_67.skeleton} />
                  <skinnedMesh name="Object_69" geometry={nodes.Object_69.geometry} material={materials.Deer_head1} skeleton={nodes.Object_69.skeleton} />
                  <skinnedMesh name="Object_71" geometry={nodes.Object_71.geometry} material={materials.Deer_head1} skeleton={nodes.Object_71.skeleton} />
                  <skinnedMesh name="Object_73" geometry={nodes.Object_73.geometry} material={materials.Deer_head1} skeleton={nodes.Object_73.skeleton} />
                  <skinnedMesh name="Object_75" geometry={nodes.Object_75.geometry} material={materials.Deer_head1} skeleton={nodes.Object_75.skeleton} />
                  <skinnedMesh name="Object_77" geometry={nodes.Object_77.geometry} material={materials.Deer_head1} skeleton={nodes.Object_77.skeleton} />
                  <skinnedMesh name="Object_79" geometry={nodes.Object_79.geometry} material={materials.Deer_head1} skeleton={nodes.Object_79.skeleton} />
                  <skinnedMesh name="Object_81" geometry={nodes.Object_81.geometry} material={materials.Deer_head1} skeleton={nodes.Object_81.skeleton} />
                  <skinnedMesh name="Object_83" geometry={nodes.Object_83.geometry} material={materials.Deer_head1} skeleton={nodes.Object_83.skeleton} />
                  <skinnedMesh name="Object_85" geometry={nodes.Object_85.geometry} material={materials.Deer_head1} skeleton={nodes.Object_85.skeleton} />
                  <skinnedMesh name="Object_87" geometry={nodes.Object_87.geometry} material={materials.Deer_head1} skeleton={nodes.Object_87.skeleton} />
                  <skinnedMesh name="Object_89" geometry={nodes.Object_89.geometry} material={materials.Deer_head1} skeleton={nodes.Object_89.skeleton} />
                  <skinnedMesh name="Object_91" geometry={nodes.Object_91.geometry} material={materials.Deer_head1} skeleton={nodes.Object_91.skeleton} />
                  <skinnedMesh name="Object_93" geometry={nodes.Object_93.geometry} material={materials.Deer_head1} skeleton={nodes.Object_93.skeleton} />
                  <skinnedMesh name="Object_95" geometry={nodes.Object_95.geometry} material={materials.Deer_head1} skeleton={nodes.Object_95.skeleton} />
                  <skinnedMesh name="Object_97" geometry={nodes.Object_97.geometry} material={materials.hair_cards_v2} skeleton={nodes.Object_97.skeleton} />
                  <skinnedMesh name="Object_99" geometry={nodes.Object_99.geometry} material={materials.hair_cards_v2} skeleton={nodes.Object_99.skeleton} />
                  <skinnedMesh name="Object_101" geometry={nodes.Object_101.geometry} material={materials.hair_cards_v2} skeleton={nodes.Object_101.skeleton} />
                  <skinnedMesh name="Object_103" geometry={nodes.Object_103.geometry} material={materials.hair_cards_v2} skeleton={nodes.Object_103.skeleton} />
                  <skinnedMesh name="Object_105" geometry={nodes.Object_105.geometry} material={materials.hair_cards_v2} skeleton={nodes.Object_105.skeleton} />
                  <skinnedMesh name="Object_107" geometry={nodes.Object_107.geometry} material={materials.hair_cards_v2} skeleton={nodes.Object_107.skeleton} />
                  <skinnedMesh name="Object_109" geometry={nodes.Object_109.geometry} material={materials.hair_cards_v2} skeleton={nodes.Object_109.skeleton} />
                  <skinnedMesh name="Object_111" geometry={nodes.Object_111.geometry} material={materials.hair_cards_v2} skeleton={nodes.Object_111.skeleton} />
                  <skinnedMesh name="Object_113" geometry={nodes.Object_113.geometry} material={materials.hair_cards_v2} skeleton={nodes.Object_113.skeleton} />
                  <skinnedMesh name="Object_115" geometry={nodes.Object_115.geometry} material={materials.hair_cards_v2} skeleton={nodes.Object_115.skeleton} />
                  <skinnedMesh name="Object_117" geometry={nodes.Object_117.geometry} material={materials.hair_cards_v2} skeleton={nodes.Object_117.skeleton} />
                  <skinnedMesh name="Object_119" geometry={nodes.Object_119.geometry} material={materials.hair_cards_v2} skeleton={nodes.Object_119.skeleton} />
                  <skinnedMesh name="Object_121" geometry={nodes.Object_121.geometry} material={materials.Hair_cards} skeleton={nodes.Object_121.skeleton} />
                  <skinnedMesh name="Object_123" geometry={nodes.Object_123.geometry} material={materials.Hair_cards} skeleton={nodes.Object_123.skeleton} />
                  <skinnedMesh name="Object_125" geometry={nodes.Object_125.geometry} material={materials.Hair_cards} skeleton={nodes.Object_125.skeleton} />
                  <skinnedMesh name="Object_127" geometry={nodes.Object_127.geometry} material={materials.Hair_cards} skeleton={nodes.Object_127.skeleton} />
                  <skinnedMesh name="Object_129" geometry={nodes.Object_129.geometry} material={materials.Hair_cards} skeleton={nodes.Object_129.skeleton} />
                  <skinnedMesh name="Object_131" geometry={nodes.Object_131.geometry} material={materials.Hair_cards} skeleton={nodes.Object_131.skeleton} />
                  <skinnedMesh name="Object_133" geometry={nodes.Object_133.geometry} material={materials.Hair_cards} skeleton={nodes.Object_133.skeleton} />
                  <skinnedMesh name="Object_135" geometry={nodes.Object_135.geometry} material={materials.Hair_cards} skeleton={nodes.Object_135.skeleton} />
                  <skinnedMesh name="Object_137" geometry={nodes.Object_137.geometry} material={materials.Hair_cards} skeleton={nodes.Object_137.skeleton} />
                  <skinnedMesh name="Object_139" geometry={nodes.Object_139.geometry} material={materials.Hair_cards} skeleton={nodes.Object_139.skeleton} />
                  <skinnedMesh name="Object_141" geometry={nodes.Object_141.geometry} material={materials.Hair_cards} skeleton={nodes.Object_141.skeleton} />
                  <skinnedMesh name="Object_143" geometry={nodes.Object_143.geometry} material={materials.Hair_cards} skeleton={nodes.Object_143.skeleton} />
                  <skinnedMesh name="Object_145" geometry={nodes.Object_145.geometry} material={materials.Hair_cards} skeleton={nodes.Object_145.skeleton} />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}
