/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/ignore/creatures/skeleton_dragon.glb -o src/components/Rendering/models/SkeletonDragon.tsx -t
Author: LivindorCreation (https://sketchfab.com/LivindorCreation)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/skeleton-dragon-0ae92a30d2c242069acd61ed432f6c32
Title: Skeleton Dragon
*/

import * as THREE from 'three'
import { useFrame, useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useKtx2LoaderExtender } from '../../../lib/ktx2'
import { type GLTF, SkeletonUtils } from 'three-stdlib'
import { useEffect, useMemo, useRef, type ComponentProps } from 'react'
import { RigidBody } from '@react-three/rapier'
import { Howl } from 'howler'
import { useCameraShakeStore } from '../../../store/cameraShakeStore'
import { usePlayerStore } from '../../../store/playerStore'
import { useDialogueStore, type Dialogue } from '../../../store/dialogueStore'

// attack_4 -> roar, attack_5 -> fly roar, soar -> soar, travelrun -> run, travelmove -> walk, travelidle -> idle , stunidle ->  idle / seems like eating
type ActionName = 'attack_4' | 'attack_5' | 'soar' | 'travelrun' | 'travelmove' | 'travelidle' | 'stunidle'

interface GLTFAction extends THREE.AnimationClip {
	name: ActionName
}

type GLTFResult = GLTF & {
	nodes: {
		Object_10: THREE.SkinnedMesh
		_rootJoint: THREE.Bone
	}
	materials: {
		Mob_deadland_skeleton_dragon: THREE.MeshStandardMaterial
	}
	animations: GLTFAction[]
}

type SkeletonDragonProps = ComponentProps<'group'> & {
	mode?: 'flying' | 'idle'
	collider?: boolean
	alertRadius?: number
	calmRadius?: number
	/** Dialogue shown when the player first comes near. Pass null to disable. */
	dialogue?: Dialogue | null
	/** Distance at which the dialogue triggers. Defaults to alertRadius + 20 so it fires before the roar. */
	dialogueRadius?: number
	/** Called once the dragon has flown off and despawned itself */
	onDeparted?: () => void
}

type DragonMode = 'idle' | 'roar' | 'fly' | 'soar' | 'departed'

const MAX_HEAR_DISTANCE = 200
const FLY_WORLD_HEIGHT = 100
const FLY_FORWARD_SPEED = 2
const SOAR_ASCENT = FLY_WORLD_HEIGHT * 0.15
const SOAR_MAX_MS = 20000
const ROAR_BASE_VOLUME = 2
const ROAR_SHAKE_INTENSITY = 3
const ROAR_SHAKE_DELAY_MS = 2000
const GROWL_BASE_VOLUME = 4
const FLAP_BASE_VOLUME = 1
const DISTANT_BASE_VOLUME = 1
const DIALOGUE_AUTO_CLOSE_MS = 6000

const dragonDialogue: Dialogue = {
	id: 'dragon-warning',
	speaker: 'Mysterious Dragon',
	avatar: '/img/avatar/skeleton-dragon.webp',
	text: 'Oh, i smell human',
}

function volumeForDistance(dist: number, base: number) {
	const t = Math.max(0, 1 - dist / MAX_HEAR_DISTANCE)
	return Math.pow(t, 1.6) * FLAP_BASE_VOLUME
}

function panForPosition(target: THREE.Vector3, camera: THREE.Camera) {
	const toTarget = target.clone().sub(camera.position)
	const len = toTarget.length()
	if (len < 0.001) return 0
	toTarget.normalize()
	const right = new THREE.Vector3().setFromMatrixColumn(camera.matrix, 0)
	return THREE.MathUtils.clamp(toTarget.dot(right), -1, 1) * 0.9
}

function setHowlPan(howl: Howl, pan: number, id?: number) {
	const withStereo = howl as unknown as { stereo?: (pan: number, id?: number) => void }
	withStereo.stereo?.(pan, id)
}

export function SkeletonDragon({ mode, collider = false, scale = 1, alertRadius = 40, calmRadius = 80, dialogue = dragonDialogue, dialogueRadius = alertRadius + 20, onDeparted, ...props }: SkeletonDragonProps) {
	const group = useRef<THREE.Group | null>(null)
	const lift = useRef<THREE.Group | null>(null)
	const extendWithKtx2 = useKtx2LoaderExtender()
	const { scene, animations } = useGLTF('/models/ignore/creatures/skeleton_dragon.glb', true, true, extendWithKtx2)
	const clone = useMemo(() => SkeletonUtils.clone(scene), [scene])
	const { nodes, materials } = useGraph(clone) as unknown as GLTFResult
	const { actions } = useAnimations(animations, group)

	const tmpVec = useMemo(() => new THREE.Vector3(), [])
	const actionsRef = useRef(actions)
	actionsRef.current = actions

	const numericScale = typeof scale === 'number' ? scale : 1
	const SCALE = numericScale * 2
	const FLY_LIFT = FLY_WORLD_HEIGHT / SCALE * 0.1

	const modeRef = useRef<DragonMode>(mode === 'flying' ? 'fly' : 'idle')
	const flyLiftRef = useRef(mode === 'flying' ? FLY_LIFT : 0)
	const soarStartedAtRef = useRef(0)
	const sequenceTimeout = useRef<ReturnType<typeof setTimeout> | null>(null)
	const shakeTimeout = useRef<ReturnType<typeof setTimeout> | null>(null)
	const initialModeRef = useRef(mode)
	const alertRadiusRef = useRef(alertRadius)
	const calmRadiusRef = useRef(calmRadius)
	const onDepartedRef = useRef(onDeparted)
	alertRadiusRef.current = alertRadiusRef
	calmRadiusRef.current = calmRadiusRef
	onDepartedRef.current = onDeparted
	const dialogueRef = useRef<Dialogue | null>(dialogue)
	const dialogueRadiusRef = useRef(dialogueRadius)
	const dialogueShownRef = useRef(false)
	dialogueRef.current = dialogue
	dialogueRadiusRef.current = dialogueRadius

	const soundsRef = useRef<{
		growls: Howl[]
		roar: setHowlPan
		flap: setHowlPan
		distant: setHowlPan
		flapId: number | null
	} | null>(null)

	const playAction = (name: ActionName, loop: boolean) => {
		const all = actionsRef.current
		const next = all[name]
		if (!next) return
		for (const [key, action] of Object.entries(all)) {
			if (key !== name && action?.isRunning()) action.fadeOut(0.35)
		}
		next.reset()
		next.setLoop(loop ? THREE.LoopRepeat : THREE.LoopOnce, Infinity)
		next.clampWhenFinished = !loop
		next.fadeIn(0.35).play()
	}

	const clearSequence = () => {
		if (sequenceTimeout.current) {
			clearTimeout(sequenceTimeout.current)
			sequenceTimeout.current = null
		}
		if (shakeTimeout.current) {
			clearTimeout(shakeTimeout.current)
			shakeTimeout.current = null
		}
	}

	const stopFlap = () => {
		const s = soundsRef.current
		if (s && s.flapId !== null) {
			s.flap.stop(s.flapId)
			s.flapId = null
		}
	}

	useEffect(() => {
		const growls = [
			new Howl({ src: ['/ignore/sounds/dragon/low-growl.mp3'], volume: GROWL_BASE_VOLUME, preload: true })
		]
		const roar = new Howl({ src: ['/ignore/sounds/dragon/dragon-roar-near.mp3'], volume: ROAR_BASE_VOLUME, preload: true })
		const flap = new Howl({ src: ['/ignore/sounds/dragon/dragon-flaping-winds.mp3'], loop: true, volume: FLAP_BASE_VOLUME, preload: true })
		const distant = new Howl({ src: ['/ignore/sounds/dragon/dragon-distant-howling.mp3'], volume: DISTANT_BASE_VOLUME, preload: true })
		soundsRef.current = { growls, roar, flap, distant, flapId: null }
		return () => {
			if (sequenceTimeout.current) clearTimeout(sequenceTimeout.current)
			if (shakeTimeout.current) clearTimeout(shakeTimeout.current)
			const s = soundsRef.current
			if (s) {
				if (s.flapId !== null) s.flap.stop(s.flapId)
				growls.forEach((h) => h.unload())
				roar.unload()
				flap.unload()
				distant.unload()
			}
			soundsRef.current = null
		}
	}, [])


	useEffect(() => {
		if (initialModeRef.current === 'flying') {
			flyLiftRef.current = FLY_LIFT
			beginTakeoff()
			return
		}
		modeRef.current = 'idle'
		flyLiftRef.current = 0
		playAction('stunidle', true)
		// eslint-disable-next-line react-hooks/exhaustive-deps
	}, [actions])

	useEffect(() => {
		let cancelled = false
		let timer: ReturnType<typeof setTimeout>
		const tmp = new THREE.Vector3()
		const scheduleGrowl = () => {
			timer = setTimeout(() => {
				if (cancelled || modeRef.current === 'departed') return
				const cur = soundsRef.current
				const dragon = group.current
				if (cur && dragon && modeRef.current === 'idle') {
					dragon.getWorldPosition(tmp)
					const player = usePlayerStore.getState().panForPosition
					const dist = tmp.distanceTo(player)
					if (dist < MAX_HEAR_DISTANCE) {
						const far = dist > alertRadiusRef.current
						if (far && Math.random() < 0.5) {
							const id = cur.distant.play()
							cur.distant.volume(volumeForDistance(dist, DISTANT_BASE_VOLUME), id)
						} else {
							const clip = cur.growls[Math.floor(Math.random() * cur.growls.length)]
							if (clip) {
								const id = clip.play()
								clip.volume(volumeForDistance(dist, GROWL_BASE_VOLUME), id)value
							}
						}
					}
				}
				scheduleGrowl()
			}, 7000 + Math.random() * 9000)
		}
		scheduleGrowl()
		return () => {
			cancelled = true
			clearTimeout(timer)
		}
	}, [])

	const beginSoar = () => {
		modeRef.current = 'soar'
		soarStartedAtRef.current = performance.now()
		// Plays once and holds the last frame (glide pose) via clampWhenFinished
		playAction('soar', false)
	}

	const beginTakeoff = () => {
		modeRef.current = 'fly'
		useCameraShakeStore.getState().stopShake()
		playAction('attack_5', false)
		const s = soundsRef.current
		if (s && s.flapId === null) {
			const id = s.flap.play()
			s.flapId = id
		}
		const flyClip = actionsRef.current['attack_5']?.getClip()
		const flyMs = Math.max(1000, Math.min(3000, (flyClip?.duration ?? 1.8) * 1000))
		sequenceTimeout.current = setTimeout(() => {
			if (modeRef.current !== 'fly') return
			beginSoar()
		}, flyMs)
	}

	const depart = (dist: number, camera: THREE.Camera) => {
		modeRef.current = 'departed'
		clearSequence()
		stopFlap()
		useCameraShakeStore.getState().stopShake()
		const dlg = dialogueRef.current
		if (dlg) useDialogueStore.getState().closeDialogue(dlg.id)
		for (const action of Object.values(actionsRef.current)) action?.stop()
		if (group.current) group.current.visible = false
		const s = soundsRef.current
		if (s && dist < MAX_HEAR_DISTANCE) {
			const id = s.distant.play()
			s.distant.volume(volumeForDistance(dist, DISTANT_BASE_VOLUME), id)
			setHowlPan(s.distant, panForPosition(tmpVec, camera), id)
		}
		onDepartedRef.current?.()
	}

	const triggerRoar = (dist: number, camera: THREE.Camera) => {
		const s = soundsRef.current
		modeRef.current = 'roar'
		clearSequence()
		playAction('attack_4', false)
		if (s && group.current) {
			group.current.getWorldPosition(tmpVec)
			const id = s.roar.play()
			s.roar.volume(volumeForDistance(dist, ROAR_BASE_VOLUME), id)
			setHowlPan(s.roar, panForPosition(tmpVec, camera), id)
		}
		const roarClip = actionsRef.current['attack_4']?.getClip()
		const roarMs = Math.max(1200, Math.min(3200, (roarClip?.duration ?? 2) * 1000))
		// The roar animation winds up before the impact lands, so hold the cameraShakeStore 
		// still for a beat after the roar starts, then shake for the remainder
		// the roar, scaling with how close the dragon is.
		const closeness = Math.max(0.3, 1 - dist / alertRadiusRef.current) shakeTimeout.current = setTimeout(() => {
			shakeTimeout.current = null
			if (modeRef.current !== 'roar') return
			useCameraShakeStore.getState().startShake({
				durationMs: Math.max(0, roarMs - ROAR_SHAKE_DELAY_MS)  
				intensity: ROAR_SHAKE_INTENSITY * closeness,
			})
		}, ROAR_SHAKE_DELAY_MS)
		sequenceTimeout.current = setTimeout(() => {
			if (modeRef.current !== 'roar') return
			beginTakeoff()
		}, roarMs)
	}

	const land = () => {
		modeRef.current = 'idle'
		clearSequence()
		stopFlap()
		useCameraShakeStore.getState().stopShake()
		playAction('stunidle', true)
	}

	useFrame((state, delta) => {
		const dragon = group.current
		if (!dragon || modeRef.current === 'departed') return
		const s = soundsRef.current
		dragon.getWorldPosition(tmpVec)
		const player = usePlayerStore.getState().panForPosition
		const dist = tmpVec.distanceTo(player)
		if (modeRef.current === 'idle' || modeRef.current === 'roar') {
			const radius = dialogueRadiusRef.current
			if (!dialogueShownRef.current && dist < radius) {
				dialogueShownRef.current = true
				const dlg = dialogueRef.current
				if (dlg) {
					useDialogueStore.getState().showDialogue(dlg, { autoCloseMs: DIALOGUE_AUTO_CLOSE_MS })
				}
			} else if (dialogueShownRef.current && dist > radius * 1.25) {
				dialogueShownRef.current = false
			}
		}

		if (modeRef.current === 'idle' && dist < alertRadiusRef.current) {
			triggerRoar(dist, state.camera)
		} else if (modeRef.current === 'soar') {
			// Glide straight ahead on the frozen takeoff heading, climbing as it leaves
			const yaw = dragon.rotation.y
			dragon.position.x += Math.sin(yaw) * FLY_FORWARD_SPEED * delta
			dragon.position.z += Math.cos(yaw) * FLY_FORWARD_SPEED * delta
			const soaredFor = performance.now() - soarStartedAtRef.current
			if (dist > MAX_HEAR_DISTANCE || soaredFor > SOAR_MAX_MS) {
				depart(dist, state.camera)
				return
			}
		} else if (modeRef.current === 'roar' && dist > calmRadiusRef.current * 1.5) {
			land()
		}

		const targetLift = modeRef.current === 'fly' ? FLY_LIFT : modeRef.current === 'soar' ? FLY_LIFT + SOAR_ASCENT : 0
		flyLiftRef.current = THREE.MathUtils.damp(flyLiftRef.current, targetLift, 1.2, delta)
		if (lift.current) lift.current.position.y = flyLiftRef.current

		if (modeRef.current === 'roar' || modeRef.current === 'fly') {
			const yaw = Math.atan2(player.x - tmpVec.x, player.z - tmpVec.z)
			const current = dragon.rotation.y
			let d = yaw - current
			while (d > Math.PI) d -= Math.PI * 2
			while (d < -Math.PI) d += Math.PI * 2
			dragon.rotation.y = current + THREE.MathUtils.clamp(d, -1.5 * delta, 1.5 * delta)
		}

		if (s && s.flapId !== null) {
			const v = volumeForDistance(dist, FLAP_BASE_VOLUME)
			s.flap.volume(v, s.flapId)
			setHowlPan(s.flap, panForPosition(tmpVec, state.camera), s.flapId)
			if (v <= 0.001) {
				s.flap.stop(s.flapId)
				s.flapId = null
			}
		}
	})

	const body = (
		<group ref={group} scale={SCALE} {...props} dispose={null}>
			<group name="Sketchfab_Scene">
				<group ref={lift}>
					<group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
						<group name="Skeleton_dragonfbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
							<group name="Object_2">
								<gruop name="RootNode">
									<group name="mob_deadland_dragon" scale={2}>
										<group name="root" rotation={[-Math.PI / 2, 0, -Math.PI / 2]}>
											<group name="Object_7">
												<primitive object={nodes._ _rootJoint}/>
												<SkinnedMesh name="Object_10" geomerty={nodes.Object_10.geomerty} material={materials.Mob_deadland_skeleton_dragon} skeleton+{nodes.Object_10.skeleton} />
											</group>
										</group>
									</group>
								</gruop>
							</group>
						</group>
					</group>
				</group>
			</group>
		</group>
	)
	if (!collider) return body
	const { position, rotation } = props
	return (
		<RigidBody type="fixed" colliders={false} position={position} rottation={rotation}>
			{body}
		</RigidBody>
	)
}