/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/ignore/map/the_last_stronghold_animated_floating.glb -o src/components/Rendering/map/StrongHoldAnimated.tsx 
Author: Conrad Justin (https://sketchfab.com/ConradJustin)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/the-last-stronghold-animated-6b4ac951cefb43a791b2bd084b53a201
Title: The Last Stronghold (animated)
*/

import * as THREE from 'three'
import { useEffect, useMemo, useRef, type JSX } from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useKtx2LoaderExtender } from '../../../lib/ktx2'
import { BallCollider, ConeCollider, CuboidCollider, RigidBody } from '@react-three/rapier'
import { type GLTF, SkeletonUtils } from 'three-stdlib'

import type { SpawnZone } from '../../World/worldTypes'
import { getAssetUrl } from '../../../pathRegistry'

type ActionName = 'Scene'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    Object_18: THREE.SkinnedMesh
    Object_20: THREE.SkinnedMesh
    Object_22: THREE.SkinnedMesh
    Object_24: THREE.SkinnedMesh
    Object_26: THREE.SkinnedMesh
    Object_28: THREE.SkinnedMesh
    Object_30: THREE.SkinnedMesh
    Object_32: THREE.SkinnedMesh
    Object_34: THREE.SkinnedMesh
    Object_36: THREE.SkinnedMesh
    _rootJoint: THREE.Bone
  }
  materials: {
    sky_sketchfab: THREE.MeshPhysicalMaterial
    final_gate_low: THREE.MeshPhysicalMaterial
    final_alfa: THREE.MeshPhysicalMaterial
    final_gate_top: THREE.MeshPhysicalMaterial
    final_C: THREE.MeshPhysicalMaterial
    final_B: THREE.MeshPhysicalMaterial
    final_SOMT: THREE.MeshPhysicalMaterial
    final_E: THREE.MeshPhysicalMaterial
    final_A: THREE.MeshPhysicalMaterial
    final_rope: THREE.MeshPhysicalMaterial
  }
  animations: GLTFAction[]
}

type Vec3 = [number, number, number]

/** One fixed physics primitive derived from an instance of a mesh in the collider GLB. */
type ColliderSpec =
  | { shape: 'cuboid'; args: [number, number, number]; position: Vec3; rotation: Vec3 }
  | { shape: 'ball'; args: [number]; position: Vec3; rotation: Vec3 }
  | { shape: 'cone'; args: [number, number]; position: Vec3; rotation: Vec3 }

const MODEL_URL = getAssetUrl('stronghold')
const COLLIDER_URL = getAssetUrl('stronghold_collider')

/**
 * Spawn zones: the standable tops of the collider floors (COL_FLOOR_*), read
 * straight off each collider instance (position, footprint, top surface) in
 * component space — World renders this map at mapScale = 10. Format:
 * [x, z, radius, floorY]. Only the reachable spawn floors are listed.
 */
export const StrongHoldSpawnZones: SpawnZone[] = [
  [10.15, -3.85, 0.63, -2.86],  // COL_FLOOR_1  far east island ledge
  [0.37, -3.27, 0.76, -0.13],   // COL_FLOOR_3
  [-5.15, 5.58, 0.87, 12.86],   // COL_FLOOR_11 keep tower top
  [4.04, -2.36, 0.99, -1.39],   // COL_FLOOR_6  east hanging island platform
  [3.79, 0.53, 0.55, -1.96],    // COL_FLOOR_7
  [1.76, 4.24, 0.58, -0.66],    // COL_FLOOR_8
  [-0.87, 5.47, 1.24, -0.02],   // COL_FLOOR_9
  [-0.85, -4.9, 0.94, 9.86],    // COL_FLOOR_10 south deck top
]

export function StrongHoldAnimated(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group | null>(null);
  const extendWithKtx2 = useKtx2LoaderExtender()
  const { scene, animations } = useGLTF(MODEL_URL, true, true, extendWithKtx2)
  const { scene: colliderScene } = useGLTF(COLLIDER_URL, true, true, extendWithKtx2)
  const clone = useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone) as unknown as GLTFResult
  const { actions } = useAnimations(animations, group)

  useEffect(() => {
    actions.Scene?.reset().fadeIn(0.5).play()
    return () => {
      actions.Scene?.fadeOut(0.5)
    }
  }, [actions])

  /**
   * Collision comes from the dedicated collider GLB. Its meshes are never
   * rendered — we read each mesh/instance's world transform (including the
   * collider's own node hierarchy) and turn it into a cheap fixed primitive:
   *   - `Cube.001`   instanced boxes   -> CuboidCollider (floors / platforms)
   *   - `Sphere`     instanced spheres -> BallCollider
   *   - `COL_CONE_*` cone meshes       -> ConeCollider
   * This replaces the previous skinned trimesh colliders (see git history),
   * which were far more expensive and had to be baked by hand. The float
   * animation (~±0.5 m bob) is still not tracked — colliders stay at bind pose.
   */
  const colliders = useMemo(() => {
    const specs: ColliderSpec[] = []
    const worldMatrix = new THREE.Matrix4()
    const instanceMatrix = new THREE.Matrix4()
    const position = new THREE.Vector3()
    const quaternion = new THREE.Quaternion()
    const scale = new THREE.Vector3()
    const euler = new THREE.Euler()
    const half = new THREE.Vector3()

    colliderScene.updateMatrixWorld(true)
    colliderScene.traverse((object) => {
      const mesh = object as THREE.Mesh
      if (!mesh.isMesh) return

      // Geometry is authored in unit space, so its bbox is the primitive's
      // base half-extents and the instance/mesh scale stretches it to size.
      mesh.geometry.computeBoundingBox()
      const bounds = mesh.geometry.boundingBox
      if (bounds) bounds.getSize(half).multiplyScalar(0.5)
      else half.set(1, 1, 1)

      const shape: ColliderSpec['shape'] = mesh.name.startsWith('COL_CONE')
        ? 'cone'
        : mesh.name.startsWith('Sphere')
          ? 'ball'
          : 'cuboid'

      const instanced = (mesh as THREE.InstancedMesh).isInstancedMesh
      const count = instanced ? (mesh as THREE.InstancedMesh).count : 1

      for (let i = 0; i < count; i++) {
        worldMatrix.copy(mesh.matrixWorld)
        if (instanced) {
          instanceMatrix.fromArray((mesh as THREE.InstancedMesh).instanceMatrix.array, i * 16)
          worldMatrix.multiply(instanceMatrix)
        }
        worldMatrix.decompose(position, quaternion, scale)
        euler.setFromQuaternion(quaternion)

        const spec = {
          position: [position.x, position.y, position.z] as Vec3,
          rotation: [euler.x, euler.y, euler.z] as Vec3,
        }
        // Rapier only has circular balls/cones, so non-uniform instances collapse
        // to their largest radial extent to avoid clipping through the mesh.
        if (shape === 'ball') {
          specs.push({ shape, args: [half.x * Math.max(Math.abs(scale.x), Math.abs(scale.y), Math.abs(scale.z))], ...spec })
        } else if (shape === 'cone') {
          specs.push({ shape, args: [half.y * Math.abs(scale.y), half.x * Math.max(Math.abs(scale.x), Math.abs(scale.z))], ...spec })
        } else {
          specs.push({ shape, args: [half.x * Math.abs(scale.x), half.y * Math.abs(scale.y), half.z * Math.abs(scale.z)], ...spec })
        }
      }
    })

    return specs
  }, [colliderScene])

  return (
    <group ref={group} {...props} dispose={null}>
      <RigidBody type="fixed" colliders={false}>
        {colliders.map((collider, i) => {
          if (collider.shape === 'ball') return <BallCollider key={i} args={collider.args} position={collider.position} rotation={collider.rotation} />
          if (collider.shape === 'cone') return <ConeCollider key={i} args={collider.args} position={collider.position} rotation={collider.rotation} />
          return <CuboidCollider key={i} args={collider.args} position={collider.position} rotation={collider.rotation} />
        })}
        <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[Math.PI / 2, 0, Math.PI]} scale={0.002}>
          <group name="ed9a8042c54c452db47145e9a7551210fbx" rotation={[-Math.PI, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="merged_gate" rotation={[0, 0, -Math.PI / 2]} scale={100} />
                <group name="merged_gate003" rotation={[0, 0, -Math.PI / 2]} scale={100} />
                <group name="merged_gate005" rotation={[0, 0, -Math.PI / 2]} scale={100} />
                <group name="merged_gate006" rotation={[0, 0, -Math.PI / 2]} scale={100} />
                <group name="merged_gate007" rotation={[0, 0, -Math.PI / 2]} scale={100} />
                <group name="merged_gate008" rotation={[0, 0, -Math.PI / 2]} scale={100} />
                <group name="merged_gate009" rotation={[0, 0, -Math.PI / 2]} scale={100} />
                <group name="merged_gate010" rotation={[0, 0, -Math.PI / 2]} scale={100} />
                <group name="merged_gate011" rotation={[0, 0, -Math.PI / 2]} scale={100} />
                <group name="merged_gate012" rotation={[0, 0, -Math.PI / 2]} scale={100} />
                <group name="Armature" rotation={[0, 0, -Math.PI / 2]} scale={100}>
                  <group name="Object_15">
                    <primitive object={nodes._rootJoint} />
                    <group name="Object_17" rotation={[0, 0, -Math.PI / 2]} scale={100} />
                    <group name="Object_19" rotation={[0, 0, -Math.PI / 2]} scale={100} />
                    <group name="Object_21" rotation={[0, 0, -Math.PI / 2]} scale={100} />
                    <group name="Object_23" rotation={[0, 0, -Math.PI / 2]} scale={100} />
                    <group name="Object_25" rotation={[0, 0, -Math.PI / 2]} scale={100} />
                    <group name="Object_27" rotation={[0, 0, -Math.PI / 2]} scale={100} />
                    <group name="Object_29" rotation={[0, 0, -Math.PI / 2]} scale={100} />
                    <group name="Object_31" rotation={[0, 0, -Math.PI / 2]} scale={100} />
                    <group name="Object_33" rotation={[0, 0, -Math.PI / 2]} scale={100} />
                    <group name="Object_35" rotation={[0, 0, -Math.PI / 2]} scale={100} />
                    <skinnedMesh name="Object_18" geometry={nodes.Object_18.geometry} material={materials.sky_sketchfab} skeleton={nodes.Object_18.skeleton} />
                    <skinnedMesh name="Object_20" geometry={nodes.Object_20.geometry} material={materials.final_gate_low} skeleton={nodes.Object_20.skeleton} />
                    <skinnedMesh name="Object_22" geometry={nodes.Object_22.geometry} material={materials.final_alfa} skeleton={nodes.Object_22.skeleton} />
                    <skinnedMesh name="Object_24" geometry={nodes.Object_24.geometry} material={materials.final_gate_top} skeleton={nodes.Object_24.skeleton} />
                    <skinnedMesh name="Object_26" geometry={nodes.Object_26.geometry} material={materials.final_C} skeleton={nodes.Object_26.skeleton} />
                    <skinnedMesh name="Object_28" geometry={nodes.Object_28.geometry} material={materials.final_B} skeleton={nodes.Object_28.skeleton} />
                    <skinnedMesh name="Object_30" geometry={nodes.Object_30.geometry} material={materials.final_SOMT} skeleton={nodes.Object_30.skeleton} />
                    <skinnedMesh name="Object_32" geometry={nodes.Object_32.geometry} material={materials.final_E} skeleton={nodes.Object_32.skeleton} />
                    <skinnedMesh name="Object_34" geometry={nodes.Object_34.geometry} material={materials.final_A} skeleton={nodes.Object_34.skeleton} />
                    <skinnedMesh name="Object_36" geometry={nodes.Object_36.geometry} material={materials.final_rope} skeleton={nodes.Object_36.skeleton} />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
      </RigidBody>
    </group>
  )
}
