/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/ignore/map/the_last_stronghold_animated_floating.glb -o src/components/Rendering/map/StrongHoldAnimated.tsx 
Author: Conrad Justin (https://sketchfab.com/ConradJustin)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/the-last-stronghold-animated-6b4ac951cefb43a791b2bd084b53a201
Title: The Last Stronghold (animated)
*/

import * as THREE from 'three'
import { useEffect, useMemo, useRef, type JSX } from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useKtx2LoaderExtender } from '../../../libs/ktx2'
import { RigidBody, TrimeshCollider } from '@react-three/rapier'
import { type GLTF, SkeletonUtils } from 'three-stdlib'

import type { SpawnZone } from '../../World/WorldTypes'

type ActionName = 'Scene'

interface GLTFAction extends THREE.AnimationClip {
    name: ActionName
}

type GLTFResult = GLTF & {
    nodes: {
        Object_18: THREE.SkinnedMesh
        Object_20: THREE.SkinnedMesh
        Object_22: THREE.SkinnedMesh
        Object_24: THREE.SkinnedMesh
        Object_26: THREE.SkinnedMesh
        Object_28: THREE.SkinnedMesh
        Object_30: THREE.SkinnedMesh
        Object_32: THREE.SkinnedMesh
        Object_34: THREE.SkinnedMesh
        Object_36: THREE.SkinnedMesh
        _rootJoint: THREE.Bone
    }
    materials: {
        sky_sketchfab: THREE.MeshPhysicalMaterial
        final_gate_low: THREE.MeshPhysicalMaterial
        final_alfa: THREE.MeshPhysicalMaterial
        final_gate_top: THREE.MeshPhysicalMaterial
        final_C: THREE.MeshPhysicalMaterial
        final_B: THREE.MeshPhysicalMaterial
        final_SOMT: THREE.MeshPhysicalMaterial
        final_E: THREE.MeshPhysicalMaterial
        final_A: THREE.MeshPhysicalMaterial
        final_rope: THREE.MeshPhysicalMaterial
    }
    animations: GLTFAction[]
}

export const StrongHoldSpawnZones: SpawnZone[] = [
    [3.9, -2.5, 0.7, -1.5],
    [-0.7, -5.0, 0.6, 9.3],
    [-4.5, 1.5, 0.7, 8.5],
    [-4.9, 5.4, 0.4, 13.1],
    [10.4, -3.9, 0.4, -2.6],
]

export function StrongHoldAnimated(props: JSX.IntrinsicElements['group']) {
    const group = useRef<THREE.Group | null>(null);
    const extendWithKtx2 = useKtx2LoaderExtender()
    const { scene, animations } = useGLTF('/models/ignore/map/the_last_stronghold_animated_floating.glb', true, true, extendWithKtx2)
    const clone = useMemo(() => SkeletonUtils.clone(scene), [scene])
    const { nodes, materials } = useGraph(clone) as unknown as GLTFResult
    const { actions } = useAnimations(animations, group)

    useEffect(() => {
        actions.Scene?.reset().fadeIn(0.5).play()
        return () => {
            actions.Scene?.fadeOut(0.5)
        }
    }, [actions])

    const colliderData = useMemo(() => {
        clone.updateMatrixWorld(true)
        const data: Array<{ vertices: Float32Array; indices: Uint32Array }> = []
        const vertex = new THREE.Vector3()
        const skinned = new THREE.Vector3()
        const temp = new THREE.Vector3()
        const boneMatrix = new THREE.Matrix4()
        clone.traverse((obj) => {
            const mesh = obj as THREE.SkinnedMesh
            if (!mesh.isSkinnedMesh) return
            const material = Array.isArray(mesh.material) ? mesh.material[0] : mesh.material
            if (material?.name.includes('sky')) return
            const position = mesh.geometry.attributes.position
            const skinIndex = mesh.geometry.attributes.skinIndex
            const skinWeight = mesh.geometry.attributes.skinWeight
            const vertices = new Float32Array(position.count * 3)
            for (let i = 0; i < position.count; i++) {
                vertex.fromBufferAttribute(position, i).applyMatrix4(mesh.bindMatrix)
                skinned.set(0, 0, 0)
                for (let k = 0; k < 4; k++) {
                    const weight = skinWeight.getComponent(i, k)
                    if (weight === 0) continue
                    const bone = skinIndex.getComponent(i, k)
                    boneMatrix.multiplyMatrices(mesh.skeleton.bones[bone].matrixWorld, mesh.skeleton.boneInverses[bone])
                    skinned.add(temp.copy(vertex).applyMatrix4(boneMatrix).multiplyScalar(weight))
                }
                skinned.applyMatrix4(mesh.bindMatrixInverse).applyMatrix4(mesh.matrixWorld)
                vertices[i * 3] = skinned.x
                vertices[i * 3 + 1] = skinned.y
                vertices[i * 3 + 2] = skinned.z
            }
            const indexAttr = mesh.geometry.index
            const indices = indexAttr
                ? new Uint32Array(indexAttr.array)
                : Uint32Array.from({ length: position.count }, (_, i) => i)
            data.push({ vertices, indices })
        })
        return data
    }, [clone])

    return (
        <group ref={group} {...props} dispose={null}>
            <RigidBody type="fixed" colliders={false}>
                {colliderData.map((data, i) => (
                    <TrimeshCollider key={i} args={[data.vertices, data.indices]} />
                ))}
                <group name="Sketchfab_Scene">
                    <group name="Sketchfab_model" rotation={[Math.PI / 2, 0, Math.PI]} scale={0.002}>
                        <group name="ed9a8042c54c452db47145e9a7551210fbx" rotation={[-Math.PI, 0, 0]}>
                            <group name="Object_2">
                                <group name="RootNode">
                                    <group name="merged_gate" rotation={[0, 0, -Math.PI / 2]} scale={100} />
                                    <group name="merged_gate003" rotation={[0, 0, -Math.PI / 2]} scale={100} />
                                    <group name="merged_gate005" rotation={[0, 0, -Math.PI / 2]} scale={100} />
                                    <group name="merged_gate006" rotation={[0, 0, -Math.PI / 2]} scale={100} />
                                    <group name="merged_gate007" rotation={[0, 0, -Math.PI / 2]} scale={100} />
                                    <group name="merged_gate008" rotation={[0, 0, -Math.PI / 2]} scale={100} />
                                    <group name="merged_gate009" rotation={[0, 0, -Math.PI / 2]} scale={100} />
                                    <group name="merged_gate010" rotation={[0, 0, -Math.PI / 2]} scale={100} />
                                    <group name="merged_gate011" rotation={[0, 0, -Math.PI / 2]} scale={100} />
                                    <group name="merged_gate012" rotation={[0, 0, -Math.PI / 2]} scale={100} />
                                    <group name="Armature" rotation={[0, 0, -Math.PI / 2]} scale={100}>
                                        <group name="Object_15">
                                            <primitive object={nodes._rootJoint} />
                                            <group name="Object_17" rotation={[0, 0, -Math.PI / 2]} scale={100} />
                                            <group name="Object_19" rotation={[0, 0, -Math.PI / 2]} scale={100} />
                                            <group name="Object_21" rotation={[0, 0, -Math.PI / 2]} scale={100} />
                                            <group name="Object_23" rotation={[0, 0, -Math.PI / 2]} scale={100} />
                                            <group name="Object_25" rotation={[0, 0, -Math.PI / 2]} scale={100} />
                                            <group name="Object_27" rotation={[0, 0, -Math.PI / 2]} scale={100} />
                                            <group name="Object_29" rotation={[0, 0, -Math.PI / 2]} scale={100} />
                                            <group name="Object_31" rotation={[0, 0, -Math.PI / 2]} scale={100} />
                                            <group name="Object_33" rotation={[0, 0, -Math.PI / 2]} scale={100} />
                                            <group name="Object_35" rotation={[0, 0, -Math.PI / 2]} scale={100} />
                                            <skinnedMesh name="Object_18" geometry={nodes.Object_18.geometry} material={materials.sky_sketchfab} skeleton={nodes.Object_18.skeleton} />
                                            <skinnedMesh name="Object_20" geometry={nodes.Object_20.geometry} material={materials.final_gate_low} skeleton={nodes.Object_20.skeleton} />
                                            <skinnedMesh name="Object_22" geometry={nodes.Object_22.geometry} material={materials.final_alfa} skeleton={nodes.Object_22.skeleton} />
                                            <skinnedMesh name="Object_24" geometry={nodes.Object_24.geometry} material={materials.final_gate_top} skeleton={nodes.Object_24.skeleton} />
                                            <skinnedMesh name="Object_26" geometry={nodes.Object_26.geometry} material={materials.final_C} skeleton={nodes.Object_26.skeleton} />
                                            <skinnedMesh name="Object_28" geometry={nodes.Object_28.geometry} material={materials.final_B} skeleton={nodes.Object_28.skeleton} />
                                            <skinnedMesh name="Object_30" geometry={nodes.Object_30.geometry} material={materials.final_SOMT} skeleton={nodes.Object_30.skeleton} />
                                            <skinnedMesh name="Object_32" geometry={nodes.Object_32.geometry} material={materials.final_E} skeleton={nodes.Object_32.skeleton} />
                                            <skinnedMesh name="Object_34" geometry={nodes.Object_34.geometry} material={materials.final_A} skeleton={nodes.Object_34.skeleton} />
                                            <skinnedMesh name="Object_36" geometry={nodes.Object_36.geometry} material={materials.final_rope} skeleton={nodes.Object_36.skeleton} />
                                        </group>
                                    </group>
                                </group>
                            </group>
                        </group>
                    </group>
                </group>
            </RigidBody>
        </group>
    )
}