/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/ignore/character/m4a1-gun-fps.glb -o src/components/Rendering/models/CharacterWithGun.tsx 
Author: BarcodeGames (https://sketchfab.com/barcodegames)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/m4-fps-weapon-animations-pack-v1-662fc74dda2646cfb48fc610705768ef
Title: M4 - FPS Weapon Animations Pack (v.1)
*/

import * as THREE from 'three'
import React, { type JSX } from 'react'
import { createPortal, useFrame, useGraph, useThree } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { type GLTF, SkeletonUtils } from 'three-stdlib'
import { Howl } from 'howler'
import { useKtx2LoaderExtender } from '../../../../lib/ktx2'
import { SFX_REGISTRY } from '../../../World/sfx/sfxRegistry'
import { getHitTargets, ownerOf } from '../../../World/combat/hitTargets'
import { usePlayerHudStore } from '../../../../store/playerHudStore'
import { DEFAULT_RECOIL_DURATION_MS, useCameraShakeStore } from '../../../../store/cameraShakeStore'
import { getAssetUrl } from '../../../../pathRegistry'

type ActionName = 'Draw' | 'Reload' | 'Fire' | 'Reload_Empty' | 'Holster'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    Bullet5_56x45mm_Bullet5_56x45mm_D_0: THREE.Mesh
    Mag1_M4_D_0: THREE.Mesh
    Bolt_M4_D_0: THREE.Mesh
    BoltCatch_M4_D_0: THREE.Mesh
    Trigger_M4_D_0: THREE.Mesh
    Bullet5_56x45mm_Bullet5_56x45mm_D_0_1: THREE.Mesh
    Mag2_M4_D_0: THREE.Mesh
    Safety_M4_D_0: THREE.Mesh
    Main_M4_D_0: THREE.Mesh
    Object_7: THREE.SkinnedMesh
    Object_8: THREE.SkinnedMesh
    _rootJoint: THREE.Bone
  }
  materials: {
    Bullet5_56x45mm_D: THREE.MeshStandardMaterial
    M4_D: THREE.MeshStandardMaterial
    Hand_D: THREE.MeshStandardMaterial
    Glove_D: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

/**
 * Placement of the rig in camera space, so the barrel sits down the view centre.
 *
 * The pack is authored around a static `FPS_Camera_j_01` bone at model-space
 * (0.0109, 1.5393, -0.1006) and the rifle points along the model's +Z, while a
 * three.js camera looks down -Z. Anchoring that bone on the camera and yawing
 * the rig 180° reproduces the artist's framing exactly:
 *   gun body  (-0.22, -0.09, -0.22) · foregrip hand (-0.36) · trigger hand (-0.03)
 *
 * z is pushed an extra 0.12 forward of the raw anchor: the trigger hand only
 * sits ~2.5cm ahead of the anchor, so without the nudge it falls inside the
 * camera's 0.1 near plane and gets clipped away.
 */
const VIEWMODEL_ANCHOR: [number, number, number] = [0.0109, -1.5393, -0.1]
const VIEWMODEL_YAW = Math.PI

/**
 * Barrel tip in the `Main_M4_D_0` rifle mesh's local space (its own frame — the
 * mesh sits at identity under the `Main` bone, so this is model unit space at
 * the 0.01 rig scale). Read off the mesh bounds (x[-9.4,-2.6] y[130,153.8]
 * z[-23.3,63.2]): the rifle is 86 units long on Z, the FPS_* camera joint and
 * the magazine both sit toward -Z, so the muzzle is the +Z extreme; the bore
 * mirrors the bolt/chamber height (~147) on the mesh centre line (~-6.02).
 *
 * The marker is parented to this mesh, so it inherits every bone transform and
 * stays glued to the barrel through the Draw/Fire clips for free.
 */
const MUZZLE_LOCAL: [number, number, number] = [-6.02, 147, 63.2]

/** Minimum gap between shots (~600 rpm). Also the hold-to-fire cadence. */
const FIRE_INTERVAL_MS = 100
/** Hitscan reach in meters; targets beyond it are never resolved. */
const RANGE = 100
const FIRE_FADE_IN = 0.03
/** Blend the held Draw pose back over the recoil once the Fire clip ends. */
const DRAW_RESTORE_FADE = 0.12
const FLASH_MS = 45
const FLASH_SIZE = 0.09
const FLASH_LIGHT_INTENSITY = 6
const TRACER_MS = 60
const TRACER_RADIUS = 0.012
const SHOT_VOLUME = 0.7

const TRACER_UP = new THREE.Vector3(0, 1, 0)

/** Restart `action` as a one-shot pose that holds its final frame. */
function playPoseOnce(action: THREE.AnimationAction) {
  action.reset()
  action.setLoop(THREE.LoopOnce, 1)
  action.clampWhenFinished = true
  action.play()
}

const MODEL_URL = getAssetUrl('m4a1-gun-fps')

export function Model(props: JSX.IntrinsicElements['group']) {
  const group = React.useRef<THREE.Group | null>(null)
  const extendWithKtx2 = useKtx2LoaderExtender()
  const { scene, animations } = useGLTF(MODEL_URL, true, true, extendWithKtx2)
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone) as unknown as GLTFResult
  const { actions, mixer } = useAnimations(animations, group)

  const camera = useThree((s) => s.camera)
  const sceneRoot = useThree((s) => s.scene)
  const renderer = useThree((s) => s.gl)

  const muzzleRef = React.useRef<THREE.Object3D | null>(null)
  const flashGroupRef = React.useRef<THREE.Group | null>(null)
  const flashMatRef = React.useRef<THREE.MeshBasicMaterial | null>(null)
  const flashLightRef = React.useRef<THREE.PointLight | null>(null)
  const tracerRef = React.useRef<THREE.Mesh | null>(null)
  const tracerMatRef = React.useRef<THREE.MeshBasicMaterial | null>(null)

  const raycaster = React.useMemo(() => new THREE.Raycaster(), [])
  const screenCenter = React.useMemo(() => new THREE.Vector2(0, 0), [])
  const shotSound = React.useRef<Howl | null>(null)

  const firingRef = React.useRef(false)
  const lastShotAtRef = React.useRef(0)
  const flashUntilRef = React.useRef(0)
  const tracerUntilRef = React.useRef(0)
  const fireRef = React.useRef<() => void>(() => {})

  // Equipping plays Draw once and holds it on the final frame. Nothing else
  // drives the rig, so the weapon sits in that pose until it is equipped again.
  // Gated on the clip existing: useAnimations builds its action map a tick
  // after mount.
  const drawAction = actions.Draw
  const hasDrawn = React.useRef(false)
  React.useEffect(() => {
    if (!drawAction || hasDrawn.current) return
    hasDrawn.current = true
    playPoseOnce(drawAction)
  }, [drawAction])

  // Barrel marker, parented to the rifle mesh so it tracks the animated bones.
  const gunMesh = nodes.Main_M4_D_0
  React.useEffect(() => {
    if (!gunMesh) return
    const marker = new THREE.Object3D()
    marker.name = 'Muzzle'
    marker.position.set(...MUZZLE_LOCAL)
    gunMesh.add(marker)
    muzzleRef.current = marker
    return () => {
      gunMesh.remove(marker)
      muzzleRef.current = null
    }
  }, [gunMesh])

  React.useEffect(() => {
    const howl = new Howl({ src: [SFX_REGISTRY.weapon[0]], volume: SHOT_VOLUME, preload: true })
    shotSound.current = howl
    return () => {
      howl.unload()
      shotSound.current = null
    }
  }, [])

  // A one-shot Fire recoil hands control back to the held Draw pose when it ends.
  // The Fire clip is clamped so both actions carry weight through the handover
  // — otherwise the pose would snap rather than crossfade. A completed fade-out
  // disables Draw, so re-enable it before fading back in.
  const fireAction = actions.Fire
  React.useEffect(() => {
    if (!mixer || !fireAction) return
    const onFinished = (event: { action: THREE.AnimationAction }) => {
      if (event.action !== fireAction || !drawAction) return
      fireAction.fadeOut(DRAW_RESTORE_FADE)
      drawAction.enabled = true
      drawAction.fadeIn(DRAW_RESTORE_FADE)
    }
    mixer.addEventListener('finished', onFinished)
    return () => {
      mixer.removeEventListener('finished', onFinished)
    }
  }, [mixer, fireAction, drawAction])

  // The firing routine: resolve the shot immediately, then play its feedback.
  fireRef.current = () => {
    const now = performance.now()
    if (now - lastShotAtRef.current < FIRE_INTERVAL_MS) return
    lastShotAtRef.current = now

    // 1. Raycast straight down the crosshair. Only registered hit targets are
    //    tested — never the whole scene — so environment hits cost nothing and
    //    the viewmodel can never clip its own ray.
    raycaster.setFromCamera(screenCenter, camera)
    raycaster.far = RANGE
    const targets = getHitTargets()
    const hits = targets.length > 0 ? raycaster.intersectObjects(targets.map((t) => t.root), true) : []
    const first = hits[0]
    const owner = first ? ownerOf(first.object) : undefined
    const hitPoint = first && owner ? first.point.clone() : null

    const muzzleWorld = new THREE.Vector3()
    if (muzzleRef.current) muzzleRef.current.getWorldPosition(muzzleWorld)
    else muzzleWorld.copy(camera.position)

    // 2. Hit reaction — environment resolves to no owner, so it does nothing.
    if (hitPoint && first && owner) owner.onHit(hitPoint, first.distance)

    // 3. Muzzle flash
    const flash = flashGroupRef.current
    if (flash) {
      flash.position.copy(muzzleWorld)
      flash.visible = true
    }
    if (flashMatRef.current) flashMatRef.current.opacity = 1
    if (flashLightRef.current) flashLightRef.current.intensity = FLASH_LIGHT_INTENSITY
    flashUntilRef.current = now + FLASH_MS

    // 4. Gunshot
    shotSound.current?.play()

    // 5. Recoil kick — additive to any dragon roar shake already in progress.
    useCameraShakeStore.getState().kickRecoil({ durationMs: DEFAULT_RECOIL_DURATION_MS })

    // 6. Tracer from the muzzle to the target (or out to max range on a miss).
    const tracer = tracerRef.current
    if (tracer) {
      const direction = new THREE.Vector3()
      camera.getWorldDirection(direction)
      const endPoint = hitPoint ?? muzzleWorld.clone().addScaledVector(direction, RANGE)
      const span = endPoint.clone().sub(muzzleWorld)
      const length = span.length()
      if (length > 0.001) {
        tracer.position.copy(muzzleWorld).addScaledVector(span, 0.5)
        tracer.quaternion.setFromUnitVectors(TRACER_UP, span.normalize())
        tracer.scale.set(1, length, 1)
        tracer.visible = true
        if (tracerMatRef.current) tracerMatRef.current.opacity = 1
        tracerUntilRef.current = now + TRACER_MS
      }
    }

    // 7. Recoil animation
    if (fireAction) {
      fireAction.reset()
      fireAction.setLoop(THREE.LoopOnce, 1)
      fireAction.clampWhenFinished = true
      fireAction.fadeIn(FIRE_FADE_IN).play()
      drawAction?.fadeOut(FIRE_FADE_IN)
    }
  }

  // Left mouse fires; holding it repeats at the cadence above.
  React.useEffect(() => {
    const canvas = renderer.domElement
    const canFire = () =>
      document.pointerLockElement === canvas && !usePlayerHudStore.getState().isGameOver

    const onMouseDown = (event: MouseEvent) => {
      if (event.button !== 0 || !canFire()) return
      firingRef.current = true
      fireRef.current()
    }
    const stop = () => {
      firingRef.current = false
    }

    window.addEventListener('mousedown', onMouseDown)
    window.addEventListener('mouseup', stop)
    window.addEventListener('blur', stop)
    document.addEventListener('pointerlockchange', stop)
    return () => {
      window.removeEventListener('mousedown', onMouseDown)
      window.removeEventListener('mouseup', stop)
      window.removeEventListener('blur', stop)
      document.removeEventListener('pointerlockchange', stop)
    }
  }, [renderer])

  useFrame(() => {
    const now = performance.now()

    if (firingRef.current) {
      const locked = document.pointerLockElement === renderer.domElement
      if (locked && !usePlayerHudStore.getState().isGameOver) fireRef.current()
      else firingRef.current = false
    }

    const flash = flashGroupRef.current
    if (flash) {
      const remaining = (flashUntilRef.current - now) / FLASH_MS
      if (remaining > 0) {
        flash.visible = true
        flash.scale.setScalar(0.6 + remaining * 0.6)
        if (flashMatRef.current) flashMatRef.current.opacity = remaining
        if (flashLightRef.current) flashLightRef.current.intensity = FLASH_LIGHT_INTENSITY * remaining
      } else if (flash.visible) {
        flash.visible = false
        if (flashLightRef.current) flashLightRef.current.intensity = 0
      }
    }

    const tracer = tracerRef.current
    if (tracer) {
      const remaining = (tracerUntilRef.current - now) / TRACER_MS
      if (remaining > 0) {
        if (tracerMatRef.current) tracerMatRef.current.opacity = remaining
      } else if (tracer.visible) {
        tracer.visible = false
      }
    }
  })

  return (
    <>
      <group ref={group} {...props} position={VIEWMODEL_ANCHOR} rotation-y={VIEWMODEL_YAW} dispose={null}>
        <group name="Sketchfab_Scene">
          <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
            <group name="90bb898c5cd8456e986c226c4e48dc5bfbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
              <group name="Object_2">
                <group name="RootNode">
                  <group name="Object_4">
                    <primitive object={nodes._rootJoint} />
                    <skinnedMesh name="Object_7" geometry={nodes.Object_7.geometry} material={materials.Hand_D} skeleton={nodes.Object_7.skeleton} />
                    <skinnedMesh name="Object_8" geometry={nodes.Object_8.geometry} material={materials.Glove_D} skeleton={nodes.Object_8.skeleton} />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>

      {/* Shot feedback lives at the scene root: the viewmodel group is snapped to
          the camera every tick, so the tracer (which ends at a world hit point)
          and the world-lit flash have to sit outside it. */}
      {createPortal(
        <group>
          <group ref={flashGroupRef} visible={false}>
            <mesh>
              <sphereGeometry args={[FLASH_SIZE, 8, 8]} />
              <meshBasicMaterial
                ref={flashMatRef}
                color="#ffcf87"
                transparent
                opacity={0}
                blending={THREE.AdditiveBlending}
                depthWrite={false}
                toneMapped={false}
              />
            </mesh>
            <pointLight ref={flashLightRef} color="#ffb066" intensity={0} distance={8} decay={2} />
          </group>
          <mesh ref={tracerRef} visible={false} frustumCulled={false}>
            <cylinderGeometry args={[TRACER_RADIUS, TRACER_RADIUS, 1, 6, 1, true]} />
            <meshBasicMaterial
              ref={tracerMatRef}
              color="#ffd98a"
              transparent
              opacity={0}
              blending={THREE.AdditiveBlending}
              depthWrite={false}
              toneMapped={false}
            />
          </mesh>
        </group>,
        sceneRoot,
      )}
    </>
  )
}
